custom: ["https://heliosdev.shop/p/hot-glue?utm_source=github.com&utm_campaign=github_hot_glue_repo_funding_link",
         "https://jfbcodes.com/p/hot-glue-in-depth-tutorial?utm_source=github.com&utm_campaign=github_hot_glue_repo_funding_link"]
