source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.3.10"


gem "rails", "~> 7.0.3", ">= 7.0.3.1"


gem "sprockets-rails"
gem "importmap-rails"
gem "stimulus-rails"
gem "turbo-rails"

gem "sqlite3", "~> 1.4"

gem "puma", "~> 5.0"

gem "jbuilder"
gem "devise"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "bootsnap", require: false


# gem "sassc-rails"
gem 'rake'


group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "ffaker"
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "byebug"
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  # selenium-webdriver >= 4.10 changed how ActionDispatch::SystemTestCase builds
  # the driver (Selenium Manager, capabilities kwarg) in ways actionpack 7.0.4's
  # driver setup doesn't support, breaking session boot entirely. Pin below that
  # until the app is on a newer Rails.
  gem "capybara", "< 3.40"
  gem "selenium-webdriver", "< 4.10"
  gem "rspec-retry"
end

# Use Redis for Action Cable
gem "redis", "~> 4.0"
gem 'hot-glue', path: "../"

gem "image_processing", "~> 1.12"

gem "pg", "~> 1.5"
