development:
  adapter: sqlite3
  database: ../spec/Dummy/db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: ../spec/Dummy/db/test.sqlite3
  pool: 5
  timeout: 5000