source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.4'

gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'
gem 'devise'
gem 'activerecord-pg_enum'

# gem 'webpacker', '~> 5.0'
# gem 'turbolinks', '~> 5'
# gem 'jbuilder', '~> 2.7'
# gem 'bootsnap', '>= 1.4.4', require: false
#
# group :development, :test do
#   gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
# end
#
# group :development do
#   gem 'web-console', '>= 4.1.0'
#   gem 'rack-mini-profiler', '~> 2.0'
#   gem 'listen', '~> 3.3'
#   gem 'spring'
# end
#
# group :test do
#   gem 'capybara', '>= 3.26'
#   gem 'selenium-webdriver'
#   gem 'webdrivers'
# end

