source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '7.0.3.1'
gem 'importmap-rails'
gem 'turbo-rails'

gem 'sqlite3'

gem 'bootsnap'
gem 'puma', '~> 5.0'
gem 'sass-rails', '>= 6'
gem 'devise'
gem 'activerecord-pg_enum'
gem 'hot-glue', path: "../.."

group :test, :development do
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'ffaker'
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end


# Use Redis for Action Cable
gem "redis", "~> 4.0"
