#!/bin/bash
rm -rf dummyapp/controllers/ghis_controller.rb
rm -rf dummyapp/controllers/abcs_controller.rb
rm -rf dummy/app/views/ghis/*
rm -rf dummy/app/views/abcs/*

/bin/rm -rf dummy/spec/system/


# !("application_controller.rb"|"welcome_controller.rb")
#find dummy/app/views/ -type f ! -name "application.html.erb" ! -name "welcome/index.erb" -delete
