#!/bin/bash


clean_generated_code() {
  /bin/rm app/controllers/abcs_controller.rb
  /bin/rm -rf app/views/abcs/
  /bin/rm -rf spec/system/
}



echo "test-on-test suite for Hot Glue..."

# note that the dummy/ is in the root of the repository

cd dummy

echo "setting up database..."

rake db:create db:reset db:test:prepare

../script/setup

bundle install

echo "Generating Abcs with rails generate hot_glue:scaffold Abc --gd"
rails generate hot_glue:scaffold Abc --gd


rspec spec || exit
clean_generated_code

cd ../..
