name: Test
on: [ push, pull_request ]

jobs:
  internal_tests:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database_name
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: bundle install
        run: cd dummy && bundle install && cd ..

      - name: run tests
        env:
          RUBYOPT: "-W:no-deprecated -W:no-experimental" # Suppress Rails 6 deprecation warnings for ruby 2.7
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_database_name"

        run: |
          cd dummy && bin/setup && cd ..
          bundle install 
          bundle exec rspec --fail-fast --backtrace




  system_tests:
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_database_name
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: bundle install
        run: cd dummy && bundle install && cd ..

      - name: run tests
        env:
          RUBYOPT: "-W:no-deprecated -W:no-experimental" # Suppress Rails 6 deprecation warnings for ruby 2.7
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test_database_name"

        run: |
          cd dummy && bin/setup 
          bundle install && cd ..
          script/test

